version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - app

  redis:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "6379:6379"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
      - client
