version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    configs:
      - source: redis_config
        target: /usr/local/etc/redis/redis.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secret
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - CHAT_CONFIG=chat.config.ConfigDev
    depends_on:
      - redis

volumes:
  redis_data:

configs:
  redis_config:
    file: ./db/redis.conf
