version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  web:
    build: .
    container_name: web
    environment:
      REDIS_ENDPOINT_URL: redis:6379
      REDIS_PASSWORD: password@123
    depends_on:
      - redis
    command: python app.py

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - client
