apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: mdasif74/python-redis-client
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://app-service:8080"
      imagePullSecrets:
      - name: regcred # if you need imagePullSecrets, otherwise remove this